### ISSUE TITLE
Missing 'main' in package.json

### ISSUE THREAD

**Issue by emmercm** [g-plane/cue#1]
I'm not entirely sure why, but the fact that `package.json` has an `exports` property and _not_ a `main` property is breaking Jest for me.

My imports look like this:

```javascript
import {
  File as CueFile, parse, Track, TrackDataType,
} from '@gplane/cue';
```

and I'm running Jest like this:

```shell
node --experimental-vm-modules ./node_modules/jest/bin/jest.js --verbose
```

and I'm getting the TypeScript error:

```text
error TS2307: Cannot find module '@gplane/cue' or its corresponding type declarations.

    8 } from '@gplane/cue';
             ~~~~~~~~~~~~~
```

If I remove the `exports` property and replace it with `"main": "./dist/index.js"` the problem goes away for me.

It seems to only be Jest, I'm able to run my app fine like this:

```shell
node --loader ts-node/esm index.ts
```

---

Some version info:

- Node.js v20.11.1
- TypeScript v5.3.3
- `jest` v29.7.0
- `ts-jest` v10.9.2
- With a fairly vanilla `tsconfig.json`:

  ```json
  {
    "compilerOptions": {
      "target": "es6",                              
      "experimentalDecorators": true,               
      "emitDecoratorMetadata": true,                
      "module": "node16",                           
      "moduleResolution": "node16",                 
      "declaration": true,                          
      "sourceMap": true,                            
      "outDir": "./dist",                           
      "esModuleInterop": true,                      
      "forceConsistentCasingInFileNames": true,     
      "strict": true,                               
      "skipLibCheck": true                          
    },
    "ts-node": {
      "esm": true,
      "experimentalSpecifierResolution": "node",
    }
  }
  ```

**Comment by g-plane** [comment]
This package is a pure ESM package.

**Comment by emmercm** [comment]
That doesn't mean the suggested change can't be made. Here are examples of pure ESM packages (no CommonJS is generated by `tsc`) I have published that don't have this issue:

- https://github.com/emmercm/chdman-js/blob/a074dcd04d23101781b04a6f7757f5f764ac2d66/package.json#L17-L25
- https://github.com/emmercm/metalsmith-plugins/blob/bef006d996570789d19e6350a1fd057d164a5dcc/packages/metalsmith-collections-related/package.json#L16-L23

**Comment by g-plane** [comment]
This package has already defined `exports` field, and there's no need to define `main` field because it will be ignored.
